
[colors]
foreground = "#A5A2A2"
background = "#090300"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#090300"
cursor_bg = "#A5A2A2"
cursor_border = "#A5A2A2"
scrollbar_thumb = "#01A0E4"

ansi = ["#5a5755", "#DB2D20", "#01A252", "#FDED02", "#01A0E4", "#A16A94", "#B5E4F4", "#A5A2A2"]
brights = ["#EDECEE", "#E8BBD0", "#928b88", "#4A4543", "#807D7C", "#D6D5D4", "#CDAB53", "#F7F7F7"]

[colors.indexed]
[metadata]
name = "3024 Night"
