
[colors]
foreground = "#637D75"
background = "#0F1610"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#0F1610"
cursor_bg = "#637D75"
cursor_border = "#637D75"
scrollbar_thumb = "#2F6A7F"

ansi = ["#627a66", "#e8877c", "#2F7E25", "#717F24", "#2F6A7F", "#47587F", "#327F77", "#647D75"]
brights = ["#EDECEE", "#E08009", "#18E000", "#BDE000", "#00AAE0", "#0058E0", "#00E0C4", "#73FA91"]

[colors.indexed]
[metadata]
name = "Alien Blood"
