
[colors]
foreground = "#968C83"
background = "#20111B"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#20111B"
cursor_bg = "#968C83"
cursor_border = "#968C83"
scrollbar_thumb = "#426A79"

ansi = ["#73616c", "#BE100E", "#858162", "#EAA549", "#426A79", "#97522C", "#989A9C", "#968C83"]
brights = ["#EDECEE", "#BE100E", "#858162", "#EAA549", "#426A79", "#97522C", "#989A9C", "#D5CCBA"]

[colors.indexed]
[metadata]
name = "Belafonte Night"
