
[colors]
foreground = "#A9BED8"
background = "#012849"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#012849"
cursor_bg = "#A9BED8"
cursor_border = "#A9BED8"
scrollbar_thumb = "#5EA2EC"

ansi = ["#817776", "#F557A0", "#A9EE55", "#F5A255", "#5EA2EC", "#A957EC", "#5EEEA0", "#918988"]
brights = ["#EDECEE", "#F579B2", "#BBEE78", "#F5B378", "#81B3EC", "#BB79EC", "#81EEB2", "#F5EEEC"]

[colors.indexed]
[metadata]
name = "Bim"
