
[colors]
foreground = "#D9E6F2"
background = "#0D1926"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#0D1926"
cursor_bg = "#D9E6F2"
cursor_border = "#D9E6F2"
scrollbar_thumb = "#7A7AB8"

ansi = ["#555555", "#B87A7A", "#7AB87A", "#B8B87A", "#7A7AB8", "#B87AB8", "#7AB8B8", "#D9D9D9"]
brights = ["#EDECEE", "#DBBDBD", "#BDDBBD", "#DBDBBD", "#BDBDDB", "#DBBDDB", "#BDDBDB", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Blazer"
