
[colors]
foreground = "#BBBBBB"
background = "#1E2229"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1E2229"
cursor_bg = "#BBBBBB"
cursor_border = "#BBBBBB"
scrollbar_thumb = "#1D99F3"

ansi = ["#70757e", "#ED1515", "#44853A", "#F67400", "#1D99F3", "#9B59B6", "#1ABC9C", "#FCFCFC"]
brights = ["#EDECEE", "#C0392B", "#55A649", "#FDBC4B", "#3DAEE9", "#8E44AD", "#16A085", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Breath Silverfox"
