
[colors]
foreground = "#D9E6F2"
background = "#29262F"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#29262F"
cursor_bg = "#D9E6F2"
cursor_border = "#D9E6F2"
scrollbar_thumb = "#7372C3"

ansi = ["#b1b1b1", "#C37372", "#72C373", "#C2C372", "#7372C3", "#C372C2", "#72C2C3", "#D9D9D9"]
brights = ["#EDECEE", "#DBAAAA", "#AADBAA", "#DADBAA", "#AAAADB", "#DBAADA", "#AADADB", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Chalkboard"
