
[colors]
foreground = "#AEA47A"
background = "#191C27"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#191C27"
cursor_bg = "#AEA47A"
cursor_border = "#AEA47A"
scrollbar_thumb = "#576D8C"

ansi = ["#696969", "#ef6e5b", "#48513B", "#CC8B3F", "#576D8C", "#724D7C", "#5C4F4B", "#AEA47F"]
brights = ["#EDECEE", "#AC3835", "#A6A75D", "#DCDF7C", "#3097C6", "#D33061", "#F3DBB2", "#F4F4F4"]

[colors.indexed]
[metadata]
name = "Ciapre"
