
[colors]
foreground = "#68525A"
background = "#150707"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#150707"
cursor_bg = "#68525A"
cursor_border = "#68525A"
scrollbar_thumb = "#8C87B0"

ansi = ["#816d6f", "#91002B", "#579524", "#AB311B", "#8C87B0", "#ca89ab", "#E8A866", "#68525A"]
brights = ["#EDECEE", "#C5255D", "#8DFF57", "#C8381D", "#CFC9FF", "#FC6CBA", "#FFCEAF", "#B0949D"]

[colors.indexed]
[metadata]
name = "Crayon Pony Fish"
