
[colors]
foreground = "#FFFFFF"
background = "#000000"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#000000"
cursor_bg = "#FFFFFF"
cursor_border = "#FFFFFF"
scrollbar_thumb = "#5555FF"

ansi = ["#555555", "#FF5555", "#55FF55", "#FFFF55", "#5555FF", "#FF55FF", "#55FFFF", "#BBBBBB"]
brights = ["#EDECEE", "#FF5555", "#55FF55", "#FFFF55", "#5555FF", "#FF55FF", "#55FFFF", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Dark Pastel"
