
[colors]
foreground = "#FFFFFF"
background = "#333333"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#333333"
cursor_bg = "#FFFFFF"
cursor_border = "#FFFFFF"
scrollbar_thumb = "#CD853F"

ansi = ["#a8a8a8", "#FF2B2B", "#98FB98", "#F0E68C", "#CD853F", "#FFDEAD", "#FFA0A0", "#F5DEB3"]
brights = ["#EDECEE", "#FF5555", "#55FF55", "#FFFF55", "#87CEFF", "#FF55FF", "#FFD700", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Desert"
