
[colors]
foreground = "#B9BCBA"
background = "#1F1F1F"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1F1F1F"
cursor_bg = "#B9BCBA"
cursor_border = "#B9BCBA"
scrollbar_thumb = "#4F76A1"

ansi = ["#92959c", "#BE3F48", "#879A3B", "#C5A635", "#4F76A1", "#855C8D", "#578FA4", "#B9BCBA"]
brights = ["#EDECEE", "#FB001F", "#0F722F", "#C47033", "#186DE3", "#FB0067", "#2E706D", "#FDFFB9"]

[colors.indexed]
[metadata]
name = "Dimmed Monokai"
