
[colors]
foreground = "#E5C7A9"
background = "#292520"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#292520"
cursor_bg = "#E5C7A9"
cursor_border = "#E5C7A9"
scrollbar_thumb = "#1398B9"

ansi = ["#626469", "#C94234", "#85C54C", "#F5AE2E", "#1398B9", "#D0633D", "#509552", "#E5C6AA"]
brights = ["#EDECEE", "#FF645A", "#98E036", "#E0D561", "#5FDAFF", "#FF9269", "#84F088", "#F6F7EC"]

[colors.indexed]
[metadata]
name = "Earthsong"
