
[colors]
foreground = "#F2F2F2"
background = "#4A453E"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#4A453E"
cursor_bg = "#F2F2F2"
cursor_border = "#F2F2F2"
scrollbar_thumb = "#729FCF"

ansi = ["#868686", "#E1321A", "#6AB017", "#FFC005", "#729FCF", "#EC0048", "#F2F2F2", "#2AA7E7"]
brights = ["#EDECEE", "#FF361E", "#7BC91F", "#FFD00A", "#0071FF", "#FF1D62", "#4BB8FD", "#ff90ff"]

[colors.indexed]
[metadata]
name = "Elic"
