
[colors]
foreground = "#DADADA"
background = "#141B1E"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#141B1E"
cursor_bg = "#DADADA"
cursor_border = "#DADADA"
scrollbar_thumb = "#67B0E8"

ansi = ["#777f82", "#E57474", "#8CCF7E", "#E5C76B", "#67B0E8", "#C47FD5", "#6CBFBF", "#B3B9B8"]
brights = ["#EDECEE", "#EF7E7E", "#96D988", "#F4D67A", "#71BAF2", "#CE89DF", "#67CBE7", "#BDC3C2"]

[colors.indexed]
[metadata]
name = "Everblush"
