
[colors]
foreground = "#1ABC9C"
background = "#1F2D3A"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1F2D3A"
cursor_bg = "#1ABC9C"
cursor_border = "#1ABC9C"
scrollbar_thumb = "#2980B9"

ansi = ["#8496ab", "#C0392B", "#27AE60", "#F39C12", "#2980B9", "#8E44AD", "#16A085", "#BDC3C7"]
brights = ["#EDECEE", "#E74C3C", "#2ECC71", "#F1C40F", "#3498DB", "#9B59B6", "#2AA198", "#ECF0F1"]

[colors.indexed]
[metadata]
name = "Flat"
