
[colors]
foreground = "#B8DBEF"
background = "#1D1F21"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1D1F21"
cursor_bg = "#B8DBEF"
cursor_border = "#B8DBEF"
scrollbar_thumb = "#5096BE"

ansi = ["#6f6f6a", "#F18339", "#9FD364", "#F4EF6D", "#5096BE", "#695ABC", "#D63865", "#FFFFFF"]
brights = ["#EDECEE", "#D22A24", "#A7D42C", "#FF8949", "#61B9D0", "#695ABC", "#D63865", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Flatland"
