
[colors]
foreground = "#D7D7DB"
background = "#2A2A2E"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#2A2A2E"
cursor_bg = "#D7D7DB"
cursor_border = "#D7D7DB"
scrollbar_thumb = "#66A05B"

ansi = ["#7f7f83", "#B98EFF", "#FF7DE9", "#729FCF", "#66A05B", "#75507B", "#ACACAE", "#FFFFFF"]
brights = ["#EDECEE", "#BF4040", "#66A05B", "#FFB86C", "#729FCF", "#8F5902", "#C4A000", "#bb8ec5"]

[colors.indexed]
[metadata]
name = "Foxnightly"
