
[colors]
foreground = "#FFFFFF"
background = "#1D2837"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1D2837"
cursor_bg = "#FFFFFF"
cursor_border = "#FFFFFF"
scrollbar_thumb = "#589DF6"

ansi = ["#b1b1b1", "#F9555F", "#21B089", "#FEF02A", "#589DF6", "#944D95", "#1F9EE7", "#BBBBBB"]
brights = ["#EDECEE", "#FA8C8F", "#35BB9A", "#FFFF55", "#589DF6", "#E75699", "#3979BC", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Frontend Galaxy"
