
[colors]
foreground = "#DEC165"
background = "#251200"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#251200"
cursor_bg = "#DEC165"
cursor_border = "#DEC165"
scrollbar_thumb = "#4699A3"

ansi = ["#555555", "#D6262B", "#919C00", "#BE8A13", "#4699A3", "#8D4331", "#DA8213", "#DDC265"]
brights = ["#EDECEE", "#E55A1C", "#BFC65A", "#FFCB1B", "#7CC9CF", "#D26349", "#E6A96B", "#FFEAA3"]

[colors.indexed]
[metadata]
name = "Frontend Fun Forrest"
