
[colors]
foreground = "#FFFFFF"
background = "#1F1E1F"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1F1E1F"
cursor_bg = "#FFFFFF"
cursor_border = "#FFFFFF"
scrollbar_thumb = "#FF004E"

ansi = ["#F9F5F5", "#CC0000", "#717071", "#ADA110", "#FF004E", "#75507B", "#06919A", "#FFFFFF"]
brights = ["#EDECEE", "#EF2929", "#FF0000", "#ADA110", "#5F4AA6", "#B74438", "#408F0C", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Geohot"
