
[colors]
foreground = "#EBEEF9"
background = "#0D101B"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#0D101B"
cursor_bg = "#EBEEF9"
cursor_border = "#EBEEF9"
scrollbar_thumb = "#58B6CA"

ansi = ["#55555b", "#BB4F6C", "#72CCAE", "#C65E3D", "#58B6CA", "#6488C4", "#8D84C6", "#858893"]
brights = ["#EDECEE", "#EE829F", "#A5FFE1", "#F99170", "#8BE9FD", "#97BBF7", "#C0B7F9", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Gooey"
