
[colors]
foreground = "#9F9FA1"
background = "#171423"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#171423"
cursor_bg = "#9F9FA1"
cursor_border = "#9F9FA1"
scrollbar_thumb = "#487DF4"

ansi = ["#837c98", "#ED2261", "#1FA91B", "#8DDC20", "#487DF4", "#8D35C9", "#3BDEED", "#9E9EA0"]
brights = ["#EDECEE", "#F0729A", "#53AA5E", "#B2DC87", "#A9BCEC", "#AD81C2", "#9DE3EB", "#A288F7"]

[colors.indexed]
[metadata]
name = "Grape"
