
[colors]
foreground = "#EBDBB2"
background = "#282828"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#282828"
cursor_bg = "#EBDBB2"
cursor_border = "#EBDBB2"
scrollbar_thumb = "#458588"

ansi = ["#7c7c7c", "#CC241D", "#98971A", "#D79921", "#458588", "#B16286", "#689D6A", "#A89984"]
brights = ["#EDECEE", "#FB4934", "#B8BB26", "#FABD2F", "#83A598", "#D3869B", "#8EC07C", "#EBDBB2"]

[colors.indexed]
[metadata]
name = "Gruvbox Dark"
