
[colors]
foreground = "#3C3836"
background = "#FBF1C7"
selection_fg = "#FF9940"
selection_bg = "#4a4543"
cursor_fg = "#FBF1C7"
cursor_bg = "#3C3836"
cursor_border = "#3C3836"
scrollbar_thumb = "#458588"

ansi = ["#ccbf74", "#CC241D", "#98971A", "#D79921", "#458588", "#B16286", "#689D6A", "#7C6F64"]
brights = ["#4a4543", "#DB7093", "#79740E", "#B57614", "#00A1F1", "#8F3F71", "#427B58", "#3C3836"]

[colors.indexed]
[metadata]
name = "Gruvbox"
