
[colors]
foreground = "#000000"
background = "#FFFFFF"
selection_fg = "#FF9940"
selection_bg = "#4a4543"
cursor_fg = "#FFFFFF"
cursor_bg = "#000000"
cursor_border = "#000000"
scrollbar_thumb = "#0000B2"

ansi = ["#000000", "#990000", "#00A600", "#999900", "#0000B2", "#B200B2", "#00A6B2", "#ae848f"]
brights = ["#4a4543", "#DB7093", "#00a900", "#aab500", "#00A1F1", "#E500E5", "#00b9bc", "#d4a8b4"]

[colors.indexed]
[metadata]
name = "Homebrew Light"
