
[colors]
foreground = "#DBDBDB"
background = "#000000"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#000000"
cursor_bg = "#DBDBDB"
cursor_border = "#DBDBDB"
scrollbar_thumb = "#496487"

ansi = ["#575757", "#FF1B00", "#A5E055", "#FBE74A", "#496487", "#FD5FF1", "#86E9FE", "#CBCCCB"]
brights = ["#EDECEE", "#D51D00", "#A5DF55", "#FBE84A", "#89BEFF", "#C001C1", "#86EAFE", "#DBDBDB"]

[colors.indexed]
[metadata]
name = "Hurtado"
