
[colors]
foreground = "#DCD7BA"
background = "#1F1F28"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1F1F28"
cursor_bg = "#DCD7BA"
cursor_border = "#DCD7BA"
scrollbar_thumb = "#7E9CD8"

ansi = ["#5a5968", "#C34043", "#76946A", "#C0A36E", "#7E9CD8", "#957FB8", "#6A9589", "#DCD7BA"]
brights = ["#EDECEE", "#E82424", "#98BB6C", "#E6C384", "#7FB4CA", "#938AA9", "#7AA89F", "#C8C093"]

[colors.indexed]
[metadata]
name = "Kanagawa"
