
[colors]
foreground = "#BDC3C7"
background = "#31363B"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#31363B"
cursor_bg = "#BDC3C7"
cursor_border = "#BDC3C7"
scrollbar_thumb = "#16A085"

ansi = ["#767776", "#ff9078", "#7E807E", "#a7aaa8", "#16A085", "#43746A", "#00CCCC", "#E0E0E0"]
brights = ["#EDECEE", "#CC372C", "#8D8F8D", "#a9adaa", "#13BF9D", "#487D72", "#00D1D1", "#E8E8E8"]

[colors.indexed]
[metadata]
name = "Maia"
