
[colors]
foreground = "#F7D66A"
background = "#120B0D"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#120B0D"
cursor_bg = "#F7D66A"
cursor_border = "#F7D66A"
scrollbar_thumb = "#515C5D"

ansi = ["#8f6d5e", "#9B291C", "#636232", "#C36E28", "#515C5D", "#9B1D29", "#588056", "#F7D75C"]
brights = ["#EDECEE", "#FF4331", "#B4B264", "#FF9566", "#9EB2B4", "#FF5B6A", "#8ACD8F", "#FFE598"]

[colors.indexed]
[metadata]
name = "Mona Lisa"
