
[colors]
foreground = "#FF9400"
background = "#2B1900"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#2B1900"
cursor_bg = "#FF9400"
cursor_border = "#FF9400"
scrollbar_thumb = "#FF9400"

ansi = ["#9e7954", "#FF9400", "#FF9400", "#FF9400", "#FF9400", "#FF9400", "#FF9400", "#FF9400"]
brights = ["#EDECEE", "#FF9400", "#FF9400", "#FF9400", "#FF9400", "#FF9400", "#FF9400", "#FF9400"]

[colors.indexed]
[metadata]
name = "Mono Amber"
