
[colors]
foreground = "#C4C5B5"
background = "#1A1A1A"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1A1A1A"
cursor_bg = "#C4C5B5"
cursor_border = "#C4C5B5"
scrollbar_thumb = "#9D65FF"

ansi = ["#6b6b6b", "#F4005F", "#98E024", "#FA8419", "#9D65FF", "#F4005F", "#58D1EB", "#C4C5B5"]
brights = ["#EDECEE", "#F4005F", "#98E024", "#E0D561", "#9D65FF", "#F4005F", "#58D1EB", "#F6F6EF"]

[colors.indexed]
[metadata]
name = "Monokai Soda"
