
[colors]
foreground = "#FDF9F3"
background = "#363537"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#363537"
cursor_bg = "#FDF9F3"
cursor_border = "#FDF9F3"
scrollbar_thumb = "#FC9867"

ansi = ["#8d8c8e", "#FF6188", "#A9DC76", "#FFD866", "#FC9867", "#AB9DF2", "#78DCE8", "#FDF9F3"]
brights = ["#EDECEE", "#FF6188", "#A9DC76", "#FFD866", "#FC9867", "#AB9DF2", "#78DCE8", "#FDF9F3"]

[colors.indexed]
[metadata]
name = "Monokai Pro"
