
[colors]
foreground = "#FFFFFF"
background = "#271F19"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#271F19"
cursor_bg = "#FFFFFF"
cursor_border = "#FFFFFF"
scrollbar_thumb = "#253B76"

ansi = ["#555555", "#ee6d54", "#61CE3C", "#FBDE2D", "#8792d7", "#FF0080", "#8DA6CE", "#F8F8F8"]
brights = ["#EDECEE", "#ee6d54", "#61CE3C", "#FBDE2D", "#8792d7", "#FF0080", "#8DA6CE", "#F8F8F8"]

[colors.indexed]
[metadata]
name = "Neopolitan"
