
[colors]
foreground = "#E6E8EF"
background = "#1C1E22"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1C1E22"
cursor_bg = "#E6E8EF"
cursor_border = "#E6E8EF"
scrollbar_thumb = "#6A7C93"

ansi = ["#767980", "#B54036", "#5AB977", "#DEB566", "#6A7C93", "#A4799D", "#3F94A8", "#E6E8EF"]
brights = ["#EDECEE", "#B54036", "#5AB977", "#DEB566", "#6A7C93", "#A4799D", "#3F94A8", "#EBEDF2"]

[colors.indexed]
[metadata]
name = "Neutron"
