
[colors]
foreground = "#BBBBBB"
background = "#000000"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#000000"
cursor_bg = "#BBBBBB"
cursor_border = "#BBBBBB"
scrollbar_thumb = "#276BD8"

ansi = ["#4C4C4C", "#BB0000", "#5FDE8F", "#F3F167", "#276BD8", "#BB00BB", "#00DADF", "#BBBBBB"]
brights = ["#EDECEE", "#FF5555", "#55FF55", "#FFFF55", "#5555FF", "#FF55FF", "#55FFFF", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Nightlion V1"
