
[colors]
foreground = "#DFDFDF"
background = "#2F2F2F"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#2F2F2F"
cursor_bg = "#DFDFDF"
cursor_border = "#DFDFDF"
scrollbar_thumb = "#1D3E6F"

ansi = ["#8f95a2", "#9B3E46", "#70b989", "#808020", "#7f96cf", "#e78dc3", "#3A7458", "#828282"]
brights = ["#EDECEE", "#D0555F", "#119955", "#DFE048", "#4674B8", "#ED86C9", "#70D2A4", "#DFDFDF"]

[colors.indexed]
[metadata]
name = "Nighty"
