
[colors]
foreground = "#979CAC"
background = "#1C1F27"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1C1F27"
cursor_bg = "#979CAC"
cursor_border = "#979CAC"
scrollbar_thumb = "#7D90A4"

ansi = ["#4F4F4F", "#AF4B57", "#AFD383", "#E5C079", "#7D90A4", "#A4799D", "#85A6A5", "#EEEDEE"]
brights = ["#EDECEE", "#AF4B57", "#CEFFAB", "#FFFECC", "#B5DCFE", "#FB9BFE", "#DFDFFD", "#FEFFFE"]

[colors.indexed]
[metadata]
name = "Ocean Dark"
