
[colors]
foreground = "#DCDFE4"
background = "#000000"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#000000"
cursor_bg = "#DCDFE4"
cursor_border = "#DCDFE4"
scrollbar_thumb = "#61AFEF"

ansi = ["#7d818b", "#E06C75", "#98C379", "#E5C07B", "#61AFEF", "#C678DD", "#56B6C2", "#DCDFE4"]
brights = ["#EDECEE", "#E06C75", "#98C379", "#E5C07B", "#61AFEF", "#C678DD", "#56B6C2", "#DCDFE4"]

[colors.indexed]
[metadata]
name = "One Half Black"
