
[colors]
foreground = "#2A2B32"
background = "#F8F8F8"
selection_fg = "#FF9940"
selection_bg = "#4a4543"
cursor_fg = "#F8F8F8"
cursor_bg = "#2A2B32"
cursor_border = "#2A2B32"
scrollbar_thumb = "#315EEE"

ansi = ["#000000", "#DA3E39", "#41933E", "#855504", "#315EEE", "#930092", "#0E6FAD", "#8E8F96"]
brights = ["#4a4543", "#DB7093", "#41933E", "#855504", "#00A1F1", "#930092", "#0E6FAD", "#f0c0c0"]

[colors.indexed]
[metadata]
name = "One Light"
