
[colors]
foreground = "#5C6370"
background = "#1E2127"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#1E2127"
cursor_bg = "#5C6370"
cursor_border = "#5C6370"
scrollbar_thumb = "#61AFEF"

ansi = ["#555555", "#E06C75", "#98C379", "#D19A66", "#61AFEF", "#C678DD", "#56B6C2", "#ABB2BF"]
brights = ["#EDECEE", "#E06C75", "#98C379", "#D19A66", "#61AFEF", "#C678DD", "#56B6C2", "#FFFEFE"]

[colors.indexed]
[metadata]
name = "One Dark"
