
[colors]
foreground = "#F6F6F7"
background = "#052454"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#052454"
cursor_bg = "#F6F6F7"
cursor_border = "#F6F6F7"
scrollbar_thumb = "#010083"

ansi = ["#555555", "#ec6d5a", "#098003", "#C4A000", "#835be7", "#D33682", "#0E807F", "#7F7C7F"]
brights = ["#EDECEE", "#EF2929", "#1CFE3C", "#FEFE45", "#268AD2", "#FE13FA", "#29FFFE", "#C2C1C3"]

[colors.indexed]
[metadata]
name = "Powershell"
