
[colors]
foreground = "#D7C9A7"
background = "#7A251E"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#7A251E"
cursor_bg = "#D7C9A7"
cursor_border = "#D7C9A7"
scrollbar_thumb = "#0072FF"

ansi = ["#000000", "#FF3F00", "#00BB00", "#E7B000", "#0072FF", "#ff89ff", "#00BBBB", "#BBBBBB"]
brights = ["#EDECEE", "#ff7f59", "#00BB00", "#E7B000", "#8bd1ff", "#FF55FF", "#55FFFF", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Red Sands"
