
[colors]
foreground = "#E0DEF4"
background = "#232136"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#232136"
cursor_bg = "#E0DEF4"
cursor_border = "#E0DEF4"
scrollbar_thumb = "#3E8FB0"

ansi = ["#928cae", "#EB6F92", "#9CCFD8", "#F6C177", "#3E8FB0", "#C4A7E7", "#EA9A97", "#E0DEF4"]
brights = ["#EDECEE", "#EB6F92", "#9CCFD8", "#F6C177", "#3E8FB0", "#C4A7E7", "#EA9A97", "#E0DEF4"]

[colors.indexed]
[metadata]
name = "Rosé Pine Moon"
