
[colors]
foreground = "#E0DEF4"
background = "#191724"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#191724"
cursor_bg = "#E0DEF4"
cursor_border = "#E0DEF4"
scrollbar_thumb = "#31748F"

ansi = ["#7b7692", "#EB6F92", "#9CCFD8", "#F6C177", "#31748F", "#C4A7E7", "#EBBCBA", "#E0DEF4"]
brights = ["#EDECEE", "#EB6F92", "#9CCFD8", "#F6C177", "#31748F", "#C4A7E7", "#EBBCBA", "#E0DEF4"]

[colors.indexed]
[metadata]
name = "Rosé Pine"
