
[colors]
foreground = "#CACECD"
background = "#111213"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#111213"
cursor_bg = "#CACECD"
cursor_border = "#CACECD"
scrollbar_thumb = "#43A5D5"

ansi = ["#888888", "#C22832", "#8EC43D", "#E0C64F", "#43A5D5", "#8B57B5", "#8EC43D", "#EEEEEE"]
brights = ["#EDECEE", "#C22832", "#8EC43D", "#E0C64F", "#43A5D5", "#8B57B5", "#8EC43D", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Seti"
