
[colors]
foreground = "#F7F7F7"
background = "#242424"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#242424"
cursor_bg = "#F7F7F7"
cursor_border = "#F7F7F7"
scrollbar_thumb = "#72B3CC"

ansi = ["#555555", "#C75646", "#8EB33B", "#D0B03C", "#72B3CC", "#C8A0D1", "#218693", "#B0B0B0"]
brights = ["#EDECEE", "#E09690", "#CDEE69", "#FFE377", "#9CD9F0", "#FBB1F9", "#77DFD8", "#F7F7F7"]

[colors.indexed]
[metadata]
name = "Smyck"
