
[colors]
foreground = "#99A3A2"
background = "#242626"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#242626"
cursor_bg = "#99A3A2"
cursor_border = "#99A3A2"
scrollbar_thumb = "#6B8FA3"

ansi = ["#555555", "#A2686A", "#9AA56A", "#A3906A", "#6B8FA3", "#6A71A3", "#6BA58F", "#99A3A2"]
brights = ["#EDECEE", "#DD5C60", "#BFDF55", "#DEB360", "#62B1DF", "#606EDF", "#64E39C", "#D2E0DE"]

[colors.indexed]
[metadata]
name = "Soft Server"
