
[colors]
foreground = "#9CC2C3"
background = "#001E27"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#001E27"
cursor_bg = "#9CC2C3"
cursor_border = "#9CC2C3"
scrollbar_thumb = "#2176C7"

ansi = ["#5a7d87", "#D11C24", "#6CBE6C", "#A57706", "#2176C7", "#C61C6F", "#259286", "#EAE3CB"]
brights = ["#EDECEE", "#F5163B", "#51EF84", "#B27E28", "#178EC8", "#E24D8E", "#00B39E", "#FCF4DC"]

[colors.indexed]
[metadata]
name = "Solarized Dark Higher Contrast"
