
[colors]
foreground = "#BDBAAE"
background = "#222222"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#222222"
cursor_bg = "#BDBAAE"
cursor_border = "#BDBAAE"
scrollbar_thumb = "#5486C0"

ansi = ["#65676e", "#EC5F67", "#81A764", "#FEC254", "#5486C0", "#BF83C1", "#57C2C1", "#EFECE7"]
brights = ["#EDECEE", "#FF6973", "#93D493", "#FFD256", "#4D84D1", "#FF55FF", "#83E9E4", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Spacegray Eighties"
