
[colors]
foreground = "#FFFFFF"
background = "#000000"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#000000"
cursor_bg = "#FFFFFF"
cursor_border = "#FFFFFF"
scrollbar_thumb = "#0084D4"

ansi = ["#555555", "#DC322F", "#56DB3A", "#FF8400", "#0084D4", "#B729D9", "#CCCCFF", "#FFFFFF"]
brights = ["#EDECEE", "#DC322F", "#56DB3A", "#FF8400", "#0084D4", "#B729D9", "#CCCCFF", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Symphonic"
