
[colors]
foreground = "#D0D0D0"
background = "#262626"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#262626"
cursor_bg = "#D0D0D0"
cursor_border = "#D0D0D0"
scrollbar_thumb = "#86AED6"

ansi = ["#6e6e6e", "#D68686", "#AED686", "#D7AF87", "#86AED6", "#D6AED6", "#8ADBB4", "#D0D0D0"]
brights = ["#EDECEE", "#D68686", "#AED686", "#E4C9AF", "#86AED6", "#D6AED6", "#B1E7DD", "#EFEFEF"]

[colors.indexed]
[metadata]
name = "Teerb"
