
[colors]
foreground = "#868A8C"
background = "#091116"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#091116"
cursor_bg = "#868A8C"
cursor_border = "#868A8C"
scrollbar_thumb = "#225555"

ansi = ["#7c7f83", "#A54242", "#A1B56C", "#DE935F", "#225555", "#85678F", "#5E8D87", "#777777"]
brights = ["#EDECEE", "#C63535", "#608360", "#FA805A", "#449DA1", "#BA8BAF", "#86C1B9", "#C5C8C6"]

[colors.indexed]
[metadata]
name = "Terminix Dark"
