
[colors]
foreground = "#FFFEFE"
background = "#002451"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#002451"
cursor_bg = "#FFFEFE"
cursor_border = "#FFFEFE"
scrollbar_thumb = "#BBDAFF"

ansi = ["#555555", "#FF9DA3", "#D1F1A9", "#FFEEAD", "#BBDAFF", "#EBBBFF", "#99FFFF", "#FFFEFE"]
brights = ["#EDECEE", "#FF9CA3", "#D0F0A8", "#FFEDAC", "#BADAFF", "#EBBAFF", "#99FFFF", "#FFFEFE"]

[colors.indexed]
[metadata]
name = "Tomorrow Night Blue"
