
[colors]
foreground = "#31D07B"
background = "#24364B"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#24364B"
cursor_bg = "#31D07B"
cursor_border = "#31D07B"
scrollbar_thumb = "#325D96"

ansi = ["#8597b5", "#BE2D26", "#1A9172", "#DB8E27", "#97b9fa", "#8A5EDC", "#35A08F", "#23D183"]
brights = ["#EDECEE", "#DD5944", "#31D07B", "#E7D84B", "#34A6DA", "#AE6BDC", "#42C3AE", "#D5D5D5"]

[colors.indexed]
[metadata]
name = "Toy Chest"
