
[colors]
foreground = "#FFFFD4"
background = "#141414"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#141414"
cursor_bg = "#FFFFD4"
cursor_border = "#FFFFD4"
scrollbar_thumb = "#44474A"

ansi = ["#646464", "#C06D44", "#AFB97A", "#C2A86C", "#9da1a4", "#B4BE7C", "#778385", "#FFFFD4"]
brights = ["#EDECEE", "#DE7C4C", "#CCD88C", "#E2C47E", "#5A5E62", "#D0DC8E", "#8A989B", "#FFFFD4"]

[colors.indexed]
[metadata]
name = "Twilight"
