
[colors]
foreground = "#D9E6F2"
background = "#191F1D"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#191F1D"
cursor_bg = "#D9E6F2"
cursor_border = "#D9E6F2"
scrollbar_thumb = "#7139A8"

ansi = ["#868686", "#A87139", "#39A871", "#71A839", "#7139A8", "#A83971", "#3971A8", "#8A8A8A"]
brights = ["#EDECEE", "#B0763B", "#3BB076", "#76B03B", "#763BB0", "#B03B76", "#3B76B0", "#CFCFCF"]

[colors.indexed]
[metadata]
name = "Vag"
