
[colors]
foreground = "#AFDAB6"
background = "#404040"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#404040"
cursor_bg = "#AFDAB6"
cursor_border = "#AFDAB6"
scrollbar_thumb = "#4261C5"

ansi = ["#000000", "#E24346", "#39B13A", "#DAE145", "#aebeff", "#F920FB", "#2ABBD4", "#D0B8A3"]
brights = ["#EDECEE", "#E97071", "#9CC090", "#DDDA7A", "#7B91D6", "#F674BA", "#5ED1E5", "#D8C8BB"]

[colors.indexed]
[metadata]
name = "Warm Neon"
