
[colors]
foreground = "#999993"
background = "#101010"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#101010"
cursor_bg = "#999993"
cursor_border = "#999993"
scrollbar_thumb = "#395573"

ansi = ["#898989", "#8C4665", "#287373", "#7C7C99", "#395573", "#5E468C", "#31658C", "#899CA1"]
brights = ["#EDECEE", "#BF4D80", "#53A6A6", "#9E9ECB", "#477AB3", "#7E62B3", "#6096BF", "#C0C0C0"]

[colors.indexed]
[metadata]
name = "Wryan"
