
[colors]
foreground = "#DCDCCC"
background = "#3F3F3F"
selection_fg = "#2196f3"
selection_bg = "#EDECEE"
cursor_fg = "#3F3F3F"
cursor_bg = "#DCDCCC"
cursor_border = "#DCDCCC"
scrollbar_thumb = "#506070"

ansi = ["#a8a8a8", "#d1acab", "#60B48A", "#F0DFAF", "#acbdcf", "#DC8CC3", "#8CD0D3", "#DCDCCC"]
brights = ["#EDECEE", "#DCA3A3", "#C3BF9F", "#E0CF9F", "#94BFF3", "#EC93D3", "#93E0E3", "#FFFFFF"]

[colors.indexed]
[metadata]
name = "Zenburn"
