require 'rainbow'
puts "\e[36mtan              \e[0m |  " + Rainbow("tan              ").tan + " |  " + Rainbow("tan              ").bg(:tan) + " |  " + Rainbow("bright 明亮").tan.bright
puts "\e[36maqua             \e[0m |  " + Rainbow("aqua             ").aqua + " |  " + Rainbow("aqua             ").bg(:aqua) + " |  " + Rainbow("bright 明亮").aqua.bright
puts "\e[36mgold             \e[0m |  " + Rainbow("gold             ").gold + " |  " + Rainbow("gold             ").bg(:gold) + " |  " + Rainbow("bright 明亮").gold.bright
puts "\e[36mgray             \e[0m |  " + Rainbow("gray             ").gray + " |  " + Rainbow("gray             ").bg(:gray) + " |  " + Rainbow("bright 明亮").gray.bright
puts "\e[36mlime             \e[0m |  " + Rainbow("lime             ").lime + " |  " + Rainbow("lime             ").bg(:lime) + " |  " + Rainbow("bright 明亮").lime.bright
puts "\e[36mperu             \e[0m |  " + Rainbow("peru             ").peru + " |  " + Rainbow("peru             ").bg(:peru) + " |  " + Rainbow("bright 明亮").peru.bright
puts "\e[36mpink             \e[0m |  " + Rainbow("pink             ").pink + " |  " + Rainbow("pink             ").bg(:pink) + " |  " + Rainbow("bright 明亮").pink.bright
puts "\e[36mplum             \e[0m |  " + Rainbow("plum             ").plum + " |  " + Rainbow("plum             ").bg(:plum) + " |  " + Rainbow("bright 明亮").plum.bright
puts "\e[36msnow             \e[0m |  " + Rainbow("snow             ").snow + " |  " + Rainbow("snow             ").bg(:snow) + " |  " + Rainbow("bright 明亮").snow.bright
puts "\e[36mteal             \e[0m |  " + Rainbow("teal             ").teal + " |  " + Rainbow("teal             ").bg(:teal) + " |  " + Rainbow("bright 明亮").teal.bright
puts "\e[36mazure            \e[0m |  " + Rainbow("azure            ").azure + " |  " + Rainbow("azure            ").bg(:azure) + " |  " + Rainbow("bright 明亮").azure.bright
puts "\e[36mbeige            \e[0m |  " + Rainbow("beige            ").beige + " |  " + Rainbow("beige            ").bg(:beige) + " |  " + Rainbow("bright 明亮").beige.bright
puts "\e[36mbrown            \e[0m |  " + Rainbow("brown            ").brown + " |  " + Rainbow("brown            ").bg(:brown) + " |  " + Rainbow("bright 明亮").brown.bright
puts "\e[36mcoral            \e[0m |  " + Rainbow("coral            ").coral + " |  " + Rainbow("coral            ").bg(:coral) + " |  " + Rainbow("bright 明亮").coral.bright
puts "\e[36mivory            \e[0m |  " + Rainbow("ivory            ").ivory + " |  " + Rainbow("ivory            ").bg(:ivory) + " |  " + Rainbow("bright 明亮").ivory.bright
puts "\e[36mkhaki            \e[0m |  " + Rainbow("khaki            ").khaki + " |  " + Rainbow("khaki            ").bg(:khaki) + " |  " + Rainbow("bright 明亮").khaki.bright
puts "\e[36mlinen            \e[0m |  " + Rainbow("linen            ").linen + " |  " + Rainbow("linen            ").bg(:linen) + " |  " + Rainbow("bright 明亮").linen.bright
puts "\e[36molive            \e[0m |  " + Rainbow("olive            ").olive + " |  " + Rainbow("olive            ").bg(:olive) + " |  " + Rainbow("bright 明亮").olive.bright
puts "\e[36mwheat            \e[0m |  " + Rainbow("wheat            ").wheat + " |  " + Rainbow("wheat            ").bg(:wheat) + " |  " + Rainbow("bright 明亮").wheat.bright
puts "\e[36mbisque           \e[0m |  " + Rainbow("bisque           ").bisque + " |  " + Rainbow("bisque           ").bg(:bisque) + " |  " + Rainbow("bright 明亮").bisque.bright
puts "\e[36mindigo           \e[0m |  " + Rainbow("indigo           ").indigo + " |  " + Rainbow("indigo           ").bg(:indigo) + " |  " + Rainbow("bright 明亮").indigo.bright
puts "\e[36mmaroon           \e[0m |  " + Rainbow("maroon           ").maroon + " |  " + Rainbow("maroon           ").bg(:maroon) + " |  " + Rainbow("bright 明亮").maroon.bright
puts "\e[36morange           \e[0m |  " + Rainbow("orange           ").orange + " |  " + Rainbow("orange           ").bg(:orange) + " |  " + Rainbow("bright 明亮").orange.bright
puts "\e[36morchid           \e[0m |  " + Rainbow("orchid           ").orchid + " |  " + Rainbow("orchid           ").bg(:orchid) + " |  " + Rainbow("bright 明亮").orchid.bright
puts "\e[36mpurple           \e[0m |  " + Rainbow("purple           ").purple + " |  " + Rainbow("purple           ").bg(:purple) + " |  " + Rainbow("bright 明亮").purple.bright
puts "\e[36msalmon           \e[0m |  " + Rainbow("salmon           ").salmon + " |  " + Rainbow("salmon           ").bg(:salmon) + " |  " + Rainbow("bright 明亮").salmon.bright
puts "\e[36msienna           \e[0m |  " + Rainbow("sienna           ").sienna + " |  " + Rainbow("sienna           ").bg(:sienna) + " |  " + Rainbow("bright 明亮").sienna.bright
puts "\e[36msilver           \e[0m |  " + Rainbow("silver           ").silver + " |  " + Rainbow("silver           ").bg(:silver) + " |  " + Rainbow("bright 明亮").silver.bright
puts "\e[36mtomato           \e[0m |  " + Rainbow("tomato           ").tomato + " |  " + Rainbow("tomato           ").bg(:tomato) + " |  " + Rainbow("bright 明亮").tomato.bright
puts "\e[36mviolet           \e[0m |  " + Rainbow("violet           ").violet + " |  " + Rainbow("violet           ").bg(:violet) + " |  " + Rainbow("bright 明亮").violet.bright
puts "\e[36mcrimson          \e[0m |  " + Rainbow("crimson          ").crimson + " |  " + Rainbow("crimson          ").bg(:crimson) + " |  " + Rainbow("bright 明亮").crimson.bright
puts "\e[36mdarkred          \e[0m |  " + Rainbow("darkred          ").darkred + " |  " + Rainbow("darkred          ").bg(:darkred) + " |  " + Rainbow("bright 明亮").darkred.bright
puts "\e[36mdimgray          \e[0m |  " + Rainbow("dimgray          ").dimgray + " |  " + Rainbow("dimgray          ").bg(:dimgray) + " |  " + Rainbow("bright 明亮").dimgray.bright
puts "\e[36mfuchsia          \e[0m |  " + Rainbow("fuchsia          ").fuchsia + " |  " + Rainbow("fuchsia          ").bg(:fuchsia) + " |  " + Rainbow("bright 明亮").fuchsia.bright
puts "\e[36mhotpink          \e[0m |  " + Rainbow("hotpink          ").hotpink + " |  " + Rainbow("hotpink          ").bg(:hotpink) + " |  " + Rainbow("bright 明亮").hotpink.bright
puts "\e[36moldlace          \e[0m |  " + Rainbow("oldlace          ").oldlace + " |  " + Rainbow("oldlace          ").bg(:oldlace) + " |  " + Rainbow("bright 明亮").oldlace.bright
puts "\e[36mskyblue          \e[0m |  " + Rainbow("skyblue          ").skyblue + " |  " + Rainbow("skyblue          ").bg(:skyblue) + " |  " + Rainbow("bright 明亮").skyblue.bright
puts "\e[36mthistle          \e[0m |  " + Rainbow("thistle          ").thistle + " |  " + Rainbow("thistle          ").bg(:thistle) + " |  " + Rainbow("bright 明亮").thistle.bright
puts "\e[36mwebgray          \e[0m |  " + Rainbow("webgray          ").webgray + " |  " + Rainbow("webgray          ").bg(:webgray) + " |  " + Rainbow("bright 明亮").webgray.bright
puts "\e[36mcornsilk         \e[0m |  " + Rainbow("cornsilk         ").cornsilk + " |  " + Rainbow("cornsilk         ").bg(:cornsilk) + " |  " + Rainbow("bright 明亮").cornsilk.bright
puts "\e[36mdarkblue         \e[0m |  " + Rainbow("darkblue         ").darkblue + " |  " + Rainbow("darkblue         ").bg(:darkblue) + " |  " + Rainbow("bright 明亮").darkblue.bright
puts "\e[36mdarkcyan         \e[0m |  " + Rainbow("darkcyan         ").darkcyan + " |  " + Rainbow("darkcyan         ").bg(:darkcyan) + " |  " + Rainbow("bright 明亮").darkcyan.bright
puts "\e[36mdarkgray         \e[0m |  " + Rainbow("darkgray         ").darkgray + " |  " + Rainbow("darkgray         ").bg(:darkgray) + " |  " + Rainbow("bright 明亮").darkgray.bright
puts "\e[36mdeeppink         \e[0m |  " + Rainbow("deeppink         ").deeppink + " |  " + Rainbow("deeppink         ").bg(:deeppink) + " |  " + Rainbow("bright 明亮").deeppink.bright
puts "\e[36mhoneydew         \e[0m |  " + Rainbow("honeydew         ").honeydew + " |  " + Rainbow("honeydew         ").bg(:honeydew) + " |  " + Rainbow("bright 明亮").honeydew.bright
puts "\e[36mlavender         \e[0m |  " + Rainbow("lavender         ").lavender + " |  " + Rainbow("lavender         ").bg(:lavender) + " |  " + Rainbow("bright 明亮").lavender.bright
puts "\e[36mmoccasin         \e[0m |  " + Rainbow("moccasin         ").moccasin + " |  " + Rainbow("moccasin         ").bg(:moccasin) + " |  " + Rainbow("bright 明亮").moccasin.bright
puts "\e[36mnavyblue         \e[0m |  " + Rainbow("navyblue         ").navyblue + " |  " + Rainbow("navyblue         ").bg(:navyblue) + " |  " + Rainbow("bright 明亮").navyblue.bright
puts "\e[36mseagreen         \e[0m |  " + Rainbow("seagreen         ").seagreen + " |  " + Rainbow("seagreen         ").bg(:seagreen) + " |  " + Rainbow("bright 明亮").seagreen.bright
puts "\e[36mseashell         \e[0m |  " + Rainbow("seashell         ").seashell + " |  " + Rainbow("seashell         ").bg(:seashell) + " |  " + Rainbow("bright 明亮").seashell.bright
puts "\e[36mwebgreen         \e[0m |  " + Rainbow("webgreen         ").webgreen + " |  " + Rainbow("webgreen         ").bg(:webgreen) + " |  " + Rainbow("bright 明亮").webgreen.bright
puts "\e[36maliceblue        \e[0m |  " + Rainbow("aliceblue        ").aliceblue + " |  " + Rainbow("aliceblue        ").bg(:aliceblue) + " |  " + Rainbow("bright 明亮").aliceblue.bright
puts "\e[36mburlywood        \e[0m |  " + Rainbow("burlywood        ").burlywood + " |  " + Rainbow("burlywood        ").bg(:burlywood) + " |  " + Rainbow("bright 明亮").burlywood.bright
puts "\e[36mcadetblue        \e[0m |  " + Rainbow("cadetblue        ").cadetblue + " |  " + Rainbow("cadetblue        ").bg(:cadetblue) + " |  " + Rainbow("bright 明亮").cadetblue.bright
puts "\e[36mchocolate        \e[0m |  " + Rainbow("chocolate        ").chocolate + " |  " + Rainbow("chocolate        ").bg(:chocolate) + " |  " + Rainbow("bright 明亮").chocolate.bright
puts "\e[36mdarkgreen        \e[0m |  " + Rainbow("darkgreen        ").darkgreen + " |  " + Rainbow("darkgreen        ").bg(:darkgreen) + " |  " + Rainbow("bright 明亮").darkgreen.bright
puts "\e[36mdarkkhaki        \e[0m |  " + Rainbow("darkkhaki        ").darkkhaki + " |  " + Rainbow("darkkhaki        ").bg(:darkkhaki) + " |  " + Rainbow("bright 明亮").darkkhaki.bright
puts "\e[36mfirebrick        \e[0m |  " + Rainbow("firebrick        ").firebrick + " |  " + Rainbow("firebrick        ").bg(:firebrick) + " |  " + Rainbow("bright 明亮").firebrick.bright
puts "\e[36mgainsboro        \e[0m |  " + Rainbow("gainsboro        ").gainsboro + " |  " + Rainbow("gainsboro        ").bg(:gainsboro) + " |  " + Rainbow("bright 明亮").gainsboro.bright
puts "\e[36mgoldenrod        \e[0m |  " + Rainbow("goldenrod        ").goldenrod + " |  " + Rainbow("goldenrod        ").bg(:goldenrod) + " |  " + Rainbow("bright 明亮").goldenrod.bright
puts "\e[36mindianred        \e[0m |  " + Rainbow("indianred        ").indianred + " |  " + Rainbow("indianred        ").bg(:indianred) + " |  " + Rainbow("bright 明亮").indianred.bright
puts "\e[36mlawngreen        \e[0m |  " + Rainbow("lawngreen        ").lawngreen + " |  " + Rainbow("lawngreen        ").bg(:lawngreen) + " |  " + Rainbow("bright 明亮").lawngreen.bright
puts "\e[36mlightblue        \e[0m |  " + Rainbow("lightblue        ").lightblue + " |  " + Rainbow("lightblue        ").bg(:lightblue) + " |  " + Rainbow("bright 明亮").lightblue.bright
puts "\e[36mlightcyan        \e[0m |  " + Rainbow("lightcyan        ").lightcyan + " |  " + Rainbow("lightcyan        ").bg(:lightcyan) + " |  " + Rainbow("bright 明亮").lightcyan.bright
puts "\e[36mlightgray        \e[0m |  " + Rainbow("lightgray        ").lightgray + " |  " + Rainbow("lightgray        ").bg(:lightgray) + " |  " + Rainbow("bright 明亮").lightgray.bright
puts "\e[36mlightpink        \e[0m |  " + Rainbow("lightpink        ").lightpink + " |  " + Rainbow("lightpink        ").bg(:lightpink) + " |  " + Rainbow("bright 明亮").lightpink.bright
puts "\e[36mlimegreen        \e[0m |  " + Rainbow("limegreen        ").limegreen + " |  " + Rainbow("limegreen        ").bg(:limegreen) + " |  " + Rainbow("bright 明亮").limegreen.bright
puts "\e[36mmintcream        \e[0m |  " + Rainbow("mintcream        ").mintcream + " |  " + Rainbow("mintcream        ").bg(:mintcream) + " |  " + Rainbow("bright 明亮").mintcream.bright
puts "\e[36mmistyrose        \e[0m |  " + Rainbow("mistyrose        ").mistyrose + " |  " + Rainbow("mistyrose        ").bg(:mistyrose) + " |  " + Rainbow("bright 明亮").mistyrose.bright
puts "\e[36molivedrab        \e[0m |  " + Rainbow("olivedrab        ").olivedrab + " |  " + Rainbow("olivedrab        ").bg(:olivedrab) + " |  " + Rainbow("bright 明亮").olivedrab.bright
puts "\e[36morangered        \e[0m |  " + Rainbow("orangered        ").orangered + " |  " + Rainbow("orangered        ").bg(:orangered) + " |  " + Rainbow("bright 明亮").orangered.bright
puts "\e[36mpalegreen        \e[0m |  " + Rainbow("palegreen        ").palegreen + " |  " + Rainbow("palegreen        ").bg(:palegreen) + " |  " + Rainbow("bright 明亮").palegreen.bright
puts "\e[36mpeachpuff        \e[0m |  " + Rainbow("peachpuff        ").peachpuff + " |  " + Rainbow("peachpuff        ").bg(:peachpuff) + " |  " + Rainbow("bright 明亮").peachpuff.bright
puts "\e[36mrosybrown        \e[0m |  " + Rainbow("rosybrown        ").rosybrown + " |  " + Rainbow("rosybrown        ").bg(:rosybrown) + " |  " + Rainbow("bright 明亮").rosybrown.bright
puts "\e[36mroyalblue        \e[0m |  " + Rainbow("royalblue        ").royalblue + " |  " + Rainbow("royalblue        ").bg(:royalblue) + " |  " + Rainbow("bright 明亮").royalblue.bright
puts "\e[36mslateblue        \e[0m |  " + Rainbow("slateblue        ").slateblue + " |  " + Rainbow("slateblue        ").bg(:slateblue) + " |  " + Rainbow("bright 明亮").slateblue.bright
puts "\e[36mslategray        \e[0m |  " + Rainbow("slategray        ").slategray + " |  " + Rainbow("slategray        ").bg(:slategray) + " |  " + Rainbow("bright 明亮").slategray.bright
puts "\e[36msteelblue        \e[0m |  " + Rainbow("steelblue        ").steelblue + " |  " + Rainbow("steelblue        ").bg(:steelblue) + " |  " + Rainbow("bright 明亮").steelblue.bright
puts "\e[36mturquoise        \e[0m |  " + Rainbow("turquoise        ").turquoise + " |  " + Rainbow("turquoise        ").bg(:turquoise) + " |  " + Rainbow("bright 明亮").turquoise.bright
puts "\e[36mwebmaroon        \e[0m |  " + Rainbow("webmaroon        ").webmaroon + " |  " + Rainbow("webmaroon        ").bg(:webmaroon) + " |  " + Rainbow("bright 明亮").webmaroon.bright
puts "\e[36mwebpurple        \e[0m |  " + Rainbow("webpurple        ").webpurple + " |  " + Rainbow("webpurple        ").bg(:webpurple) + " |  " + Rainbow("bright 明亮").webpurple.bright
puts "\e[36maquamarine       \e[0m |  " + Rainbow("aquamarine       ").aquamarine + " |  " + Rainbow("aquamarine       ").bg(:aquamarine) + " |  " + Rainbow("bright 明亮").aquamarine.bright
puts "\e[36mblueviolet       \e[0m |  " + Rainbow("blueviolet       ").blueviolet + " |  " + Rainbow("blueviolet       ").bg(:blueviolet) + " |  " + Rainbow("bright 明亮").blueviolet.bright
puts "\e[36mchartreuse       \e[0m |  " + Rainbow("chartreuse       ").chartreuse + " |  " + Rainbow("chartreuse       ").bg(:chartreuse) + " |  " + Rainbow("bright 明亮").chartreuse.bright
puts "\e[36mcornflower       \e[0m |  " + Rainbow("cornflower       ").cornflower + " |  " + Rainbow("cornflower       ").bg(:cornflower) + " |  " + Rainbow("bright 明亮").cornflower.bright
puts "\e[36mdarkorange       \e[0m |  " + Rainbow("darkorange       ").darkorange + " |  " + Rainbow("darkorange       ").bg(:darkorange) + " |  " + Rainbow("bright 明亮").darkorange.bright
puts "\e[36mdarkorchid       \e[0m |  " + Rainbow("darkorchid       ").darkorchid + " |  " + Rainbow("darkorchid       ").bg(:darkorchid) + " |  " + Rainbow("bright 明亮").darkorchid.bright
puts "\e[36mdarksalmon       \e[0m |  " + Rainbow("darksalmon       ").darksalmon + " |  " + Rainbow("darksalmon       ").bg(:darksalmon) + " |  " + Rainbow("bright 明亮").darksalmon.bright
puts "\e[36mdarkviolet       \e[0m |  " + Rainbow("darkviolet       ").darkviolet + " |  " + Rainbow("darkviolet       ").bg(:darkviolet) + " |  " + Rainbow("bright 明亮").darkviolet.bright
puts "\e[36mdodgerblue       \e[0m |  " + Rainbow("dodgerblue       ").dodgerblue + " |  " + Rainbow("dodgerblue       ").bg(:dodgerblue) + " |  " + Rainbow("bright 明亮").dodgerblue.bright
puts "\e[36mghostwhite       \e[0m |  " + Rainbow("ghostwhite       ").ghostwhite + " |  " + Rainbow("ghostwhite       ").bg(:ghostwhite) + " |  " + Rainbow("bright 明亮").ghostwhite.bright
puts "\e[36mlightcoral       \e[0m |  " + Rainbow("lightcoral       ").lightcoral + " |  " + Rainbow("lightcoral       ").bg(:lightcoral) + " |  " + Rainbow("bright 明亮").lightcoral.bright
puts "\e[36mlightgreen       \e[0m |  " + Rainbow("lightgreen       ").lightgreen + " |  " + Rainbow("lightgreen       ").bg(:lightgreen) + " |  " + Rainbow("bright 明亮").lightgreen.bright
puts "\e[36mmediumblue       \e[0m |  " + Rainbow("mediumblue       ").mediumblue + " |  " + Rainbow("mediumblue       ").bg(:mediumblue) + " |  " + Rainbow("bright 明亮").mediumblue.bright
puts "\e[36mpapayawhip       \e[0m |  " + Rainbow("papayawhip       ").papayawhip + " |  " + Rainbow("papayawhip       ").bg(:papayawhip) + " |  " + Rainbow("bright 明亮").papayawhip.bright
puts "\e[36mpowderblue       \e[0m |  " + Rainbow("powderblue       ").powderblue + " |  " + Rainbow("powderblue       ").bg(:powderblue) + " |  " + Rainbow("bright 明亮").powderblue.bright
puts "\e[36msandybrown       \e[0m |  " + Rainbow("sandybrown       ").sandybrown + " |  " + Rainbow("sandybrown       ").bg(:sandybrown) + " |  " + Rainbow("bright 明亮").sandybrown.bright
puts "\e[36mwhitesmoke       \e[0m |  " + Rainbow("whitesmoke       ").whitesmoke + " |  " + Rainbow("whitesmoke       ").bg(:whitesmoke) + " |  " + Rainbow("bright 明亮").whitesmoke.bright
puts "\e[36mdarkmagenta      \e[0m |  " + Rainbow("darkmagenta      ").darkmagenta + " |  " + Rainbow("darkmagenta      ").bg(:darkmagenta) + " |  " + Rainbow("bright 明亮").darkmagenta.bright
puts "\e[36mdeepskyblue      \e[0m |  " + Rainbow("deepskyblue      ").deepskyblue + " |  " + Rainbow("deepskyblue      ").bg(:deepskyblue) + " |  " + Rainbow("bright 明亮").deepskyblue.bright
puts "\e[36mfloralwhite      \e[0m |  " + Rainbow("floralwhite      ").floralwhite + " |  " + Rainbow("floralwhite      ").bg(:floralwhite) + " |  " + Rainbow("bright 明亮").floralwhite.bright
puts "\e[36mforestgreen      \e[0m |  " + Rainbow("forestgreen      ").forestgreen + " |  " + Rainbow("forestgreen      ").bg(:forestgreen) + " |  " + Rainbow("bright 明亮").forestgreen.bright
puts "\e[36mgreenyellow      \e[0m |  " + Rainbow("greenyellow      ").greenyellow + " |  " + Rainbow("greenyellow      ").bg(:greenyellow) + " |  " + Rainbow("bright 明亮").greenyellow.bright
puts "\e[36mlightsalmon      \e[0m |  " + Rainbow("lightsalmon      ").lightsalmon + " |  " + Rainbow("lightsalmon      ").bg(:lightsalmon) + " |  " + Rainbow("bright 明亮").lightsalmon.bright
puts "\e[36mlightyellow      \e[0m |  " + Rainbow("lightyellow      ").lightyellow + " |  " + Rainbow("lightyellow      ").bg(:lightyellow) + " |  " + Rainbow("bright 明亮").lightyellow.bright
puts "\e[36mnavajowhite      \e[0m |  " + Rainbow("navajowhite      ").navajowhite + " |  " + Rainbow("navajowhite      ").bg(:navajowhite) + " |  " + Rainbow("bright 明亮").navajowhite.bright
puts "\e[36msaddlebrown      \e[0m |  " + Rainbow("saddlebrown      ").saddlebrown + " |  " + Rainbow("saddlebrown      ").bg(:saddlebrown) + " |  " + Rainbow("bright 明亮").saddlebrown.bright
puts "\e[36mspringgreen      \e[0m |  " + Rainbow("springgreen      ").springgreen + " |  " + Rainbow("springgreen      ").bg(:springgreen) + " |  " + Rainbow("bright 明亮").springgreen.bright
puts "\e[36myellowgreen      \e[0m |  " + Rainbow("yellowgreen      ").yellowgreen + " |  " + Rainbow("yellowgreen      ").bg(:yellowgreen) + " |  " + Rainbow("bright 明亮").yellowgreen.bright
puts "\e[36mantiquewhite     \e[0m |  " + Rainbow("antiquewhite     ").antiquewhite + " |  " + Rainbow("antiquewhite     ").bg(:antiquewhite) + " |  " + Rainbow("bright 明亮").antiquewhite.bright
puts "\e[36mdarkseagreen     \e[0m |  " + Rainbow("darkseagreen     ").darkseagreen + " |  " + Rainbow("darkseagreen     ").bg(:darkseagreen) + " |  " + Rainbow("bright 明亮").darkseagreen.bright
puts "\e[36mlemonchiffon     \e[0m |  " + Rainbow("lemonchiffon     ").lemonchiffon + " |  " + Rainbow("lemonchiffon     ").bg(:lemonchiffon) + " |  " + Rainbow("bright 明亮").lemonchiffon.bright
puts "\e[36mlightskyblue     \e[0m |  " + Rainbow("lightskyblue     ").lightskyblue + " |  " + Rainbow("lightskyblue     ").bg(:lightskyblue) + " |  " + Rainbow("bright 明亮").lightskyblue.bright
puts "\e[36mmediumorchid     \e[0m |  " + Rainbow("mediumorchid     ").mediumorchid + " |  " + Rainbow("mediumorchid     ").bg(:mediumorchid) + " |  " + Rainbow("bright 明亮").mediumorchid.bright
puts "\e[36mmediumpurple     \e[0m |  " + Rainbow("mediumpurple     ").mediumpurple + " |  " + Rainbow("mediumpurple     ").bg(:mediumpurple) + " |  " + Rainbow("bright 明亮").mediumpurple.bright
puts "\e[36mmidnightblue     \e[0m |  " + Rainbow("midnightblue     ").midnightblue + " |  " + Rainbow("midnightblue     ").bg(:midnightblue) + " |  " + Rainbow("bright 明亮").midnightblue.bright
puts "\e[36mdarkgoldenrod    \e[0m |  " + Rainbow("darkgoldenrod    ").darkgoldenrod + " |  " + Rainbow("darkgoldenrod    ").bg(:darkgoldenrod) + " |  " + Rainbow("bright 明亮").darkgoldenrod.bright
puts "\e[36mdarkslateblue    \e[0m |  " + Rainbow("darkslateblue    ").darkslateblue + " |  " + Rainbow("darkslateblue    ").bg(:darkslateblue) + " |  " + Rainbow("bright 明亮").darkslateblue.bright
puts "\e[36mdarkslategray    \e[0m |  " + Rainbow("darkslategray    ").darkslategray + " |  " + Rainbow("darkslategray    ").bg(:darkslategray) + " |  " + Rainbow("bright 明亮").darkslategray.bright
puts "\e[36mdarkturquoise    \e[0m |  " + Rainbow("darkturquoise    ").darkturquoise + " |  " + Rainbow("darkturquoise    ").bg(:darkturquoise) + " |  " + Rainbow("bright 明亮").darkturquoise.bright
puts "\e[36mlavenderblush    \e[0m |  " + Rainbow("lavenderblush    ").lavenderblush + " |  " + Rainbow("lavenderblush    ").bg(:lavenderblush) + " |  " + Rainbow("bright 明亮").lavenderblush.bright
puts "\e[36mlightseagreen    \e[0m |  " + Rainbow("lightseagreen    ").lightseagreen + " |  " + Rainbow("lightseagreen    ").bg(:lightseagreen) + " |  " + Rainbow("bright 明亮").lightseagreen.bright
puts "\e[36mpalegoldenrod    \e[0m |  " + Rainbow("palegoldenrod    ").palegoldenrod + " |  " + Rainbow("palegoldenrod    ").bg(:palegoldenrod) + " |  " + Rainbow("bright 明亮").palegoldenrod.bright
puts "\e[36mpaleturquoise    \e[0m |  " + Rainbow("paleturquoise    ").paleturquoise + " |  " + Rainbow("paleturquoise    ").bg(:paleturquoise) + " |  " + Rainbow("bright 明亮").paleturquoise.bright
puts "\e[36mpalevioletred    \e[0m |  " + Rainbow("palevioletred    ").palevioletred + " |  " + Rainbow("palevioletred    ").bg(:palevioletred) + " |  " + Rainbow("bright 明亮").palevioletred.bright
puts "\e[36mrebeccapurple    \e[0m |  " + Rainbow("rebeccapurple    ").rebeccapurple + " |  " + Rainbow("rebeccapurple    ").bg(:rebeccapurple) + " |  " + Rainbow("bright 明亮").rebeccapurple.bright
puts "\e[36mblanchedalmond   \e[0m |  " + Rainbow("blanchedalmond   ").blanchedalmond + " |  " + Rainbow("blanchedalmond   ").bg(:blanchedalmond) + " |  " + Rainbow("bright 明亮").blanchedalmond.bright
puts "\e[36mdarkolivegreen   \e[0m |  " + Rainbow("darkolivegreen   ").darkolivegreen + " |  " + Rainbow("darkolivegreen   ").bg(:darkolivegreen) + " |  " + Rainbow("bright 明亮").darkolivegreen.bright
puts "\e[36mlightgoldenrod   \e[0m |  " + Rainbow("lightgoldenrod   ").lightgoldenrod + " |  " + Rainbow("lightgoldenrod   ").bg(:lightgoldenrod) + " |  " + Rainbow("bright 明亮").lightgoldenrod.bright
puts "\e[36mlightslategray   \e[0m |  " + Rainbow("lightslategray   ").lightslategray + " |  " + Rainbow("lightslategray   ").bg(:lightslategray) + " |  " + Rainbow("bright 明亮").lightslategray.bright
puts "\e[36mlightsteelblue   \e[0m |  " + Rainbow("lightsteelblue   ").lightsteelblue + " |  " + Rainbow("lightsteelblue   ").bg(:lightsteelblue) + " |  " + Rainbow("bright 明亮").lightsteelblue.bright
puts "\e[36mmediumseagreen   \e[0m |  " + Rainbow("mediumseagreen   ").mediumseagreen + " |  " + Rainbow("mediumseagreen   ").bg(:mediumseagreen) + " |  " + Rainbow("bright 明亮").mediumseagreen.bright
puts "\e[36mmediumslateblue  \e[0m |  " + Rainbow("mediumslateblue  ").mediumslateblue + " |  " + Rainbow("mediumslateblue  ").bg(:mediumslateblue) + " |  " + Rainbow("bright 明亮").mediumslateblue.bright
puts "\e[36mmediumturquoise  \e[0m |  " + Rainbow("mediumturquoise  ").mediumturquoise + " |  " + Rainbow("mediumturquoise  ").bg(:mediumturquoise) + " |  " + Rainbow("bright 明亮").mediumturquoise.bright
puts "\e[36mmediumvioletred  \e[0m |  " + Rainbow("mediumvioletred  ").mediumvioletred + " |  " + Rainbow("mediumvioletred  ").bg(:mediumvioletred) + " |  " + Rainbow("bright 明亮").mediumvioletred.bright
puts "\e[36mmediumaquamarine \e[0m |  " + Rainbow("mediumaquamarine ").mediumaquamarine + " |  " + Rainbow("mediumaquamarine ").bg(:mediumaquamarine) + " |  " + Rainbow("bright 明亮").mediumaquamarine.bright
puts "\e[36mmediumspringgreen\e[0m |  " + Rainbow("mediumspringgreen").mediumspringgreen + " |  " + Rainbow("mediumspringgreen").bg(:mediumspringgreen) + " |  " + Rainbow("bright 明亮").mediumspringgreen.bright
